export const AUTHORIZATION_ROLE_KEY = Symbol('AUTHORIZATION_ROLE_KEY');
export const AUTHORIZATION_AUTH_KEY = Symbol('AUTHORIZATION_AUTH_KEY');
export const AUTH_JWT_SECRET =
  'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.';
export const ONE_DAY = 1000 * 60 * 60 * 24;
