export const AUTHORIZATION_ROLE_KEY = Symbol('AUTHORIZATION_ROLE_KEY');
export const AUTH_JWT_SECRET =
  'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.';
